### ISSUE TITLE
Fix typos

### ISSUE THREAD

**Issue by matiasandina** [open-neuroscience/open-neuroscience.github.io#1]
Fix typos and other problems that break on posts [like this one](https://github.com/open-neuroscience/academic-kickstart/blob/master/content/en/post/optogenetics/index.md) or code formatting on [this one](https://open-neuroscience.com/staging/en/post/arduino-script-posner-test/)

**Comment by matiasandina** [comment]
This is the current state of problems
~cross out once solved~

post | problem
-- | --
~super_releaser~ | ~missing youtube link~
open-bionics | missing youtube link
prosthetics-and-robotics | relative links are broken
neuroimaging-databases | typos and outdated links, switch https://coins.trendscenter.org/
~arduino-script-posner-test~ | ~code is wrongly formatted. also consider having code as a file in github instead~
~schematics-posner-test~ | ~broken links, also consider uploading images to previous post~
microcontrollers | broken reference to https://upload.wikimedia.org/wikipedia/commons/3/31/Mbeb_microcontroller_and_pin-out.jpg
allen-brain-map | formatting
~autoreward2~ | ~links to google photos are broken~
~lab-management-software~ | ~problem with features link~
~ipipet~ | ~broken vimeo embed~
human-psychophysics-using-arduino | relative links are broken
green-brain | image embed broken
fingertip_laser_sensor | image embed broken
data-repositories | figshare broken image
data_analysis | broken internal links, also should have the paginator removed
computers | broken links and tag cards
computer-vision-and-motion-tracking-software | formatting, also probably outdated (e.g., missing DeepLabCut, simba)
computer_clusters | probably needs to be deleted
brainbrowser | formatting
bpm_biosignal | broken image
big-neuron | formatting
~microscope-software~ | ~section page, probably must be deleted~
neuromorpho | formatting, broken image ?
fingertip_laser_sensor | formatting, broken image
~nibabel~ | ~some format of the links is unnecessary~
~nipy~ | ~some links are broken~
~nose-poke-device-for-rats-using-arduino-and-3d-printed-parts~ | ~broken links~
open_hand_project | broken image
~open-lab-notebooks~ | ~outdated, links don’t take you to relevant info?~
~ome-open-microscopy-environment~ | ~broken image~
~openflexure~ | ~broken image~
~opening-mcd-files-with-python~ | ~python code does not render, also considering hosting on github instead~
~psychophysics-toolboxes~ | ~images don’t render~
~pulse-pal | broken image~
~python-posner-test~ | ~python code does not render, also considering hosting on github instead~
~raspberry-pi-based~ | ~image embed broken~
~red-pitaya~ | ~embed broken~
~school_of_data~ | ~formatting~
simulation~ | ~formatting
skinnerbox_rpi_python | some parts don’t render
~spike-gadgets~ | ~formatting is a mess~
takktile | video doesn’t show
tensor-flow | video doesn’t show
the_yale_open_hand_project | broken image
tutorials | internal links broken

**Comment by amchagas** [comment]
ha! should have checked this before.... updated #12 with a lot of overlapping information...
