### ISSUE TITLE
Come up with a more standarized post structure 

### ISSUE THREAD

**Issue by matiasandina** [open-neuroscience/open-neuroscience.github.io#11]
or will we do this just for future posts?

**Comment by amchagas** [comment]
I think we can start just having this for new posts, and the ones we will need to update due to broken links (#12 )

How about having something like:


-image/embedded video
-short paragraph
-contact info of the original developers

**Comment by matiasandina** [comment]
Yes, so the "form" would be something like? 

## Title

[INSERT IMAGE HERE]

## short paragraph

## contact info

****
This sounds reasonable enough to automate

**Comment by amchagas** [comment]
I think yeah. I mean, at least in the beginning to get things going? 
Or did you have something else in mind?

**Comment by matiasandina** [comment]
No, I was just thinking about implementation (using Google Forms?) 
I think a form with fields is the easiest for people and for us to just read a csv table and generate posts on a scheduled task, like a cron job. 

Should we send rendered preview to the authors to approve or just post and have them modify if there's a mistake?

**Comment by amchagas** [comment]
google forms plus scheduled job sounds good, as well as sending the authors the rendered page/post

**Comment by matiasandina** [comment]
TODO:

- [x] Finalize Google Forms
- [x] Figure out script to create a post from .csv results on GoogleDrive
- [ ] cron scheduling

**Comment by matiasandina** [comment]
This is mostly done on my side. I have no idea how to fix what we discussed today, so I asked on StackOverflow https://stackoverflow.com/questions/61960739/prevent-writelines-overwriting-md-files

remainder is to write the little cron job to run `autoposter.R` every once in a while

**Comment by amchagas** [comment]
Added the cron job task to a new issue so we can close this one
