### ISSUE TITLE
Discuss wordcloud utility

### ISSUE THREAD

**Issue by matiasandina** [open-neuroscience/open-neuroscience.github.io#14]
Is the wordcloud of the usage of terms accurate/looks good/functional? We can modify it or delete it as needed. The file that handles that is https://github.com/open-neuroscience/academic-kickstart/blob/master/content/en/home/tags.md

**Comment by amchagas** [comment]
After a brief discussion on Jan 12th 2022, we decided that it does not hurt to keep the word cloud.
