### ISSUE TITLE
Sort backlog

### ISSUE THREAD

**Issue by matiasandina** [open-neuroscience/open-neuroscience.github.io#15]
Sort [backlog](https://open-neuroscience.com/post/backlog/)

**Comment by matiasandina** [comment]
- [x] http://wiki.cogain.org/index.php/Eye_Trackers Low cost eye tracking
~~- [ ] http://home.gna.org/veusz/ scientific plotting package~~
- [ ] http://erkutlu.blogspot.com.es/2012/12/eeg-and-arduino-do-it-yourself-eeg-ekg.html
- [ ] http://www.wired.com/wiredscience/2011/03/diy-cellphone-microscope cellphone into microscope spectrometer
- [ ] http://www.ncbi.nlm.nih.gov/geo/ gene expression omnibus database 
~~- [ ] http://journal.frontiersin.org/Journal/10.3389/fninf.2014.00024/abstract Broccoli software for fast fMRI analyses~~
    No longer maintained 
- [ ] http://www.plosone.org/article/info%3Adoi%2F10.1371%2Fjournal.pone.0086733 smartphone brain scanner
~~- [ ] http://paper.li/IbrahimMalick/1320890343  open source by ibrahim malick~~
~~- [ ] http://www.theguardian.com/public-leaders-network/2014/apr/15/big-data-open-data-transform-government?CMP=twt_gu big data~~
~~- [ ] https://code.google.com/p/arduino-v-neusci/ example on how to use arduino for visual neuroscience~~
- [X] http://boinc.berkeley.edu/  
~~- [ ] http://pybossa.com/ the same idea from boinc (above) but sharing cognition~~
- [X] http://www.acq4.org/ neurophysiology and data analysis systems
~~- [ ] https://about.gitlab.com/about/ version control system for projects~~
~~- [ ] http://leaflabs.com/willow neuroscience 1000 channels array~~
~~- [ ] http://scalablephysiology.org/ the page dedicated to willow~~
~~- [ ] http://heywhatsthebigidea.net/projects/pi-vision-a-raspberry-pi-camera-controller/ pivision~~
~~- [ ] https://libre3d.com/category/687/Test-Equipment/listings/717/Open-Source-Water-Testing-Platform.html~~ <- off topic
~~- [ ] http://www.peekvision.org/ ophtamology exams with smartphones~~ <- off topic
~~- [ ] http://www.gpugrid.net/ distributed computing~~
~~- [ ] http://www.iorodeo.com/consulting open source hardware company~~ <- off topic?
~~- [ ] http://hackaday.com/2015/01/06/3d-printing-circuits-gets-rid-of-the-box-altogether/  3d print plastic and electronics together~~
~~- [ ] https://synbiota.com/  electronic lab notebook~~ <- no longer exists
~~- [ ] http://biojs.net/ biological data visualization tool~~
- [ ] http://open-access.net/de_en/homepage/ portal that gathers information on open access
- [ ] http://www.ohwr.org/ open hardware repository
~~- [ ] http://www.openingscience.org/ an umbrella t open scholarly data to a multitude of stakeholders~~
~~- [ ] http://woodenhaptics.org/ open source haptics device~~
~~- [ ] https://www.youtube.com/watch?v=Ss-9iXRUeGc Pneuflex actuators~~
- [ ] https://sites.google.com/site/openspinmicroscopy/ Openspin microscope
- [ ] http://openspim.org/Welcome_to_the_OpenSPIM_Wiki openspin microscope
- [x] http://journal.frontiersin.org/Journal/10.3389/fneng.2014.00043/abstract signal generator
~~- [ ] http://hackaday.io/project/1395-open-source-science-tricorder arduino based gagdet with lots of sensors~~
~~- [ ] https://plot.ly/feed/ plots and data online~~
~~- [ ] http://littledevices.org/ small portable devices for health related tests/exams and etc~~
~~- [ ] https://gnu.io/ social interaction~~
~~- [ ] http://thinklab.com/how_it_works online platform for science project management~~
~~- [ ] http://credit.casrai.org/about-us/ changing the way scientific contributions are measured/displayed~~
~~- [ ] http://journal.frontiersin.org/article/10.3389/fneng.2015.00001/full?utm_source=newsletter&utm_medium=email&utm_campaign=Neuroscience-w15-2015 system for light stimulation and data recording for optogenetics~~
~~- [ ] https://arcturus.io/~~
- [ ] http://cmictig.cs.ucl.ac.uk/wiki/index.php/Main_Page  brain imaging software suite
~~- [ ] https://openhatch.org/wiki/Open_Science_Projects_and_Organizations#Neuroscience_2   Open science projects for neurosciences~~
~~- [ ] http://openpump.org/ open source syringe pump~~
~~- [ ] http://fab.cba.mit.edu/classes/4.140/people/wildebeest/projects/final/index.html another open source pump~~
~~- [ ] http://guides.teklalabs.org/c/Science_Lab_Equipment tekla labs~~
~~- [ ] http://blogs.lse.ac.uk/impactofsocialsciences/2014/08/05/oer-impact-map-open-university/ open lectures and their impact~~
~~- [ ] http://www.graphicsmagick.org/index.html image processing library~~
~~- [ ] http://www.kinectotherapy.in/~~
- [ ] http://www.oshwa.org/ open source hardware association page
- [ ] https://www.peerageofscience.org/how-it-works/ peerage of science
~~- [ ] http://www.linux-usb-daq.co.uk/ general IO boards for linux~~
- [ ] https://pubpeer.com/ post review of papers
~~- [ ] https://opensource.com/business/15/8/open-source-products-four-rules?utm_content=buffer7c7ae&utm_medium=social&utm_source=facebook.com&utm_campaign=buffer Open source for products~~
- [ ] [http://journal.frontiersin.org/article/10.3389/fnins.2015.00206/full?utm_source=newsletter&utm_medium=email&utm_campaign=Neuroscience-w33-2015 spinnaker. millisecond](http://journal.frontiersin.org/article/10.3389/fnins.2015.00206/full?utm_source=newsletter&utm_medium=email&utm_campaign=Neuroscience-w33-2015 spinnaker. millisecond) range modelling
~~- [ ] http://wiki.openscienceschool.com/wiki/Tools/DI-Lambda do it yourself spectrophotometer~~
~~- [ ] http://thurj.org/research/2011/01/432/ automated head fixed prep for rats~~
- [ ] http://journal.frontiersin.org/article/10.3389/fninf.2015.00004/full?utm_source=newsletter&utm_medium=email&utm_campaign=Neuroscience-w17-2015 map reduce, scalable data analysis for ephys
~~- [ ] www.elsevier.com/connect/the-changing-face-of-journal-metrics the changing face of journal metrics~~
- [ ] http://www.johnstowers.co.nz/blog/2014/05/27/flymad/ fly brain altering device
- [ ] https://jupyter.org/ open source notebook for over 40 programming languages
- [ ] https://sites.google.com/site/neurorighter/ closed loop recording and stimulation ephys
~~- [ ] http://www.kitware.com/opensource/opensource.html several open source software suites/libraries~~
- [x] https://jasp-stats.org/ a fresh way to do statistics
- [X] http://www.brain-map.org/ allen institute page with data, tools and maps
~~- [ ] https://www.circuitlab.com/~~
~~- [ ] www.123dapp.com/circuits~~
- [ ] https://madresistor.org/box0/
- [ ] https://zenodo.org/
- [ ] https://ipfs.io/
~~- [ ]     The next wave in software is open adoption software~~
~~- [ ] https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4933559/pdf/1604.pdf~~
~~- [ ] https://www.rs-online.com/designspark/the-teaching-lab-of-tomorrow?cm_mmc=DE-EM-_-DSN_20160822-_-DM3300-_-TTB_URL2&cid=DM3300&bid=53290840~~
~~- [ ] http://www.nytimes.com/2016/06/28/technology/amazon-unveils-online-education-service-for-teachers.html?_r=5®ister=google~~
~~- [ ] https://www.hackster.io/arduino~~
- [ ] http://brainwaves.io/wp/
~~- [ ] http://www.mkme.org/~~
~~- [ ] https://outernet.is/~~
~~- [ ] https://hackaday.io/project/16024-openwheel-parametric-osh-wheelstyrestracks~~
~~- [ ] http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0166735#sec016~~
- [ ] https://hackaday.io/project/18643-open-source-freakin-scanning-electron-microscope  open source electron microscope
~~- [ ] http://jn.physiology.org/content/116/2/252.long Open notebooks on ephys~~
- [ ] http://www.instructables.com/id/Laser-Scanning-Microscope/ make a laser scanning microscope
- [ ] https://github.com/maxritter/DIY-Thermocam DIY thermal camera
~~- [ ] https://neuinfo.org/about/organization neuroscience information framework~~
~~- [ ] https://publishing.aip.org/publishing/journal-highlights/how-3-d-print-your-own-sonic-tractor-beam DIY sonic tractor beam~~
~~- [ ] http://www.upb.edu/en/contenido/mini-spectrometer-3d-printable-model DIY spectrometer~~
~~- [ ] https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4857158/pdf/ac5b04153.pdf lab on a drone~~
~~- [ ] http://oceanographyforeveryone.com/ page hosting hardware projects related to oceanography~~
~~- [ ] https://makingscience.withgoogle.com/science-journal?lang=en google app for data collection using mobile phone sensors ~~
~~- [ ] http://3d.si.edu/browser smithsonian museum repository of scanned objects~~
~~- [ ] https://nasa3d.arc.nasa.gov/models nasa models for 3d p nting~~
~~- [ ] http://www.qtiplot.com/ Data analysis and visualization~~
~~- [ ] https://github.com/BigCorvus/Physio hacked medical device~~
- [ ] https://mousetube.pasteur.fr/ mouse vocalization database
~~- [ ] http://www.thinkering.de/cms/ blog on tinkering with science tool examples~~

**Comment by amchagas** [comment]
think this is at least sorted in terms of still active projects and things that are useful for ON

**Comment by amchagas** [comment]
pinged projects that are still active, and just waiting for them to decide on whether they want to be added to ON or not.
