### ISSUE TITLE
Links from some posts end up in old website

### ISSUE THREAD

**Issue by amgfernandes** [open-neuroscience/open-neuroscience.github.io#18]
Links on some posts go to old website. 
Example: https://open-neuroscience.com/en/post/tutorials/

**Comment by amchagas** [comment]
Hi, I removed this one page, as the tutorials were super outdated and poorly documented. 

Could you take a look to see if you find other examples where we are still pointing to the old website? I think a lot of this got cleaned up already when we were making posts more uniform, etc.
