### ISSUE TITLE
Change configuration favicon and tab

### ISSUE THREAD

**Issue by amchagas** [open-neuroscience/open-neuroscience.github.io#2]
Right now favicon and text on browser tab are still from Sleek's theme
It would be nice to change that to Open Neuroscience's logo https://github.com/open-neuroscience/open-neuroscience.github.io/blob/master/assets/img/pages/openneuroscience_md.jpg
Most likely just the left part for the favicon

**Comment by adarshbalu** [comment]
I would like to work on this issue.

**Comment by amchagas** [comment]
Hi @adarshbalu ! Thanks for your interest and your will to contribute to Open Neuroscience. 

If you want to work on this issue, by all means, go ahead, all the necessary files are already on the repository! If you need help finding anything, let me know!

**Comment by amchagas** [comment]
Hi, just saw your PR. Thanks for working on this! I merged the changes and going to close this issue.
