### ISSUE TITLE
organize code, logo, templates on new repo

### ISSUE THREAD

**Issue by amchagas** [open-neuroscience/open-neuroscience.github.io#21]
Right now we are more or less using this repo as a central things for too many things (I think). 
It would be nice to create a new repo (or repos) to split the core website things from other "more generic ones", like message templates, logo files, functions that are part of populating the website, but not used for the website itself etc.

**Comment by amchagas** [comment]
If this seems sensible, I can implement it.

**Comment by matiasandina** [comment]
I recently did this for another organization and think this is the way to go.
How about a "resources" repo (github.com/open-neuroscience/resources) where we throw logos and all other resources that come along the way ?

**Comment by amchagas** [comment]
sounds good to me!

**Comment by matiasandina** [comment]
Done here https://github.com/open-neuroscience/resources
