### ISSUE TITLE
clap system: re-evaluate

### ISSUE THREAD

**Issue by amchagas** [open-neuroscience/open-neuroscience.github.io#38]
A while ago we implemented this "clap sytem" where people could leave a clap in case they liked a project. 

Although I think it is a nice idea, I am failing to see its usefulness, as there are very little, if any claps on the website, and I am not sure at the moment, if the claps are erased everytime we do a new deployment?

In case this turned out to be something not useful, we can simply remove the code from the website?

**Comment by matiasandina** [comment]
Claps are removed every time :scream: ?
The motivation behind claps was to have a measurement of engagement.
I think we should still try to get a measure for this, if not the claps, what better alternative can we think of?

**Comment by amchagas** [comment]
I am not entirely sure if they do get removed or not, but seems no psts have claps at the moment, so either it is getting reset, or people are not using it at all?

**Comment by amchagas** [comment]
From our last monthly meeting in Nov. 2021, we decided to scrape this from the website.
