### ISSUE TITLE
social icons at the end of the posts

### ISSUE THREAD

**Issue by matiasandina** [open-neuroscience/open-neuroscience.github.io#7]
@amchagas said he would deal with this

**Comment by amchagas** [comment]
So the social icons at the end of the posts are just an easy button for people to share the post. 
https://sourcethemes.com/academic/docs/customization/#page-sharer

doesn't require any changes from our side, and the question is whether or not we want to keep them and how many if we do. As all of them looks spammy/polluted?

**Comment by matiasandina** [comment]
Yes, sorry about not being clear.
Question was whether we want to keep them and which ones

**Comment by amchagas** [comment]
ah, ok! 
So I would say facebook, twitter, email, reddit (?), linkedin(?)
What do you think?

**Comment by matiasandina** [comment]
Sounds good

**Comment by amchagas** [comment]
done!
