### ISSUE TITLE
Complete the author pages

### ISSUE THREAD

**Issue by matiasandina** [open-neuroscience/open-neuroscience.github.io#8]
I partially completed this. We need all others to complete

- [ ] provide bio or other info for author page
- [x] social links

**Comment by matiasandina** [comment]
This is only working for Miguel ? What's the status on this ?

**Comment by amchagas** [comment]
This is already completed

**Comment by matiasandina** [comment]
On my side, the only available description that I see is for Miguel

**Comment by amchagas** [comment]
Sorry, forgot to push :P
Try now?

**Comment by matiasandina** [comment]
Ok, I'm also there now, I don't know if we have descriptions for everyone
else or not. but this should be closed then
